package main

import (
 "bufio"; "context"; "crypto/rand"; "encoding/base64"; "encoding/json"; "errors"; "fmt"; "io"; "log"; "net"; "net/http"; "os"; "os/exec"; "os/signal"; "path/filepath"; "strconv"; "strings"; "sync"; "syscall"; "time"; "unsafe"
)

const (
 configPath="/etc/lalune/gateway.json"; tokenPath="/etc/lalune/panel.token"; stateDir="/var/lib/lalune"; corePath=stateDir+"/client-linux-arm64"
 tunName="csqtt0"; tunIP="10.66.67.12"; table="200"; uds="@lalune-csqtt-tun"; panel="0.0.0.0:18787"
 coreVersion="2026.09.16.17.59"; wgName="lalune-wg"; wgSubnet="10.77.0.0/30"; wgServer="10.77.0.1/30"; wgPeer="10.77.0.2/32"; wgPort="51821"
)

type Config struct { Peer,Password,Hashes string; Workers int; Obfs,Fingerprint,ClientIDs,CaptchaMode,VKAuthMode,TurnTransport,TurnHost,TurnPort,DeviceID,WGPeerPublicKey string }
type Gateway struct { mu sync.Mutex; cfg Config; cmd *exec.Cmd; tun *os.File; connected bool; started time.Time; logs []string }

func main(){
 if os.Geteuid()!=0 {log.Fatal("run as root")}; _=os.MkdirAll(stateDir,0755); _=os.MkdirAll(filepath.Dir(configPath),0700); ensureToken(); g:=&Gateway{cfg:loadConfig()}
 g.log("[GATEWAY] start: TUN=%s table=%s WG=%s:%s panel=%s",tunName,table,wgName,wgPort,panel); if e:=g.ensureCore();e!=nil{g.log("[CORE] %v",e)}
 mux:=http.NewServeMux(); mux.HandleFunc("/api/status",g.auth(g.status)); mux.HandleFunc("/api/config",g.auth(g.configAPI)); mux.HandleFunc("/api/connect",g.auth(g.connectAPI)); mux.HandleFunc("/api/disconnect",g.auth(g.disconnectAPI)); mux.HandleFunc("/api/logs",g.auth(g.logsAPI)); mux.HandleFunc("/",g.auth(g.page)); srv:=&http.Server{Addr:panel,Handler:mux,ReadHeaderTimeout:5*time.Second}; go func(){if e:=srv.ListenAndServe();e!=nil&&!errors.Is(e,http.ErrServerClosed){log.Print(e)}}()
 ctx,stop:=signal.NotifyContext(context.Background(),syscall.SIGTERM,syscall.SIGINT); defer stop(); if g.cfg.Peer!=""&&g.cfg.Password!=""&&g.cfg.Hashes!=""{if e:=g.connect();e!=nil{g.log("[CORE] auto-connect: %v",e)}}; <-ctx.Done(); _=g.disconnect(); _=srv.Shutdown(context.Background())
}
func ensureToken(){if b,e:=os.ReadFile(tokenPath);e==nil&&strings.TrimSpace(string(b))!=""{return};b:=make([]byte,32);if _,e:=rand.Read(b);e!=nil{log.Fatal(e)};_=os.WriteFile(tokenPath,[]byte(base64.RawURLEncoding.EncodeToString(b)+"\n"),0600)}
func loadConfig()Config{d:=Config{Workers:9,Obfs:"audio",Fingerprint:"chrome",CaptchaMode:"auto",VKAuthMode:"vkcalls",TurnTransport:"udp"};b,e:=os.ReadFile(configPath);if e!=nil{return d};var c Config;if json.Unmarshal(b,&c)!=nil{return d};if c.Workers<1{c.Workers=9};if c.Obfs==""{c.Obfs="audio"};if c.Fingerprint==""{c.Fingerprint="chrome"};if c.CaptchaMode==""{c.CaptchaMode="auto"};if c.VKAuthMode==""{c.VKAuthMode="vkcalls"};if c.TurnTransport==""{c.TurnTransport="udp"};return c}
func saveConfig(c Config)error{b,_:=json.MarshalIndent(c,"","  ");return os.WriteFile(configPath,append(b,'\n'),0600)}
func(g *Gateway)log(f string,a ...any){s:=fmt.Sprintf(f,a...);log.Print(s);g.mu.Lock();defer g.mu.Unlock();g.logs=append(g.logs,s);if len(g.logs)>400{g.logs=g.logs[len(g.logs)-400:]}}
func(g *Gateway)ensureCore()error{if st,e:=os.Stat(corePath);e==nil&&st.Mode().Perm()&0111!=0{return nil};u:="https://github.com/Endlad2/csqtt-core/releases/download/"+coreVersion+"/client-linux-arm64";r,e:=http.Get(u);if e!=nil{return e};defer r.Body.Close();if r.StatusCode!=200{return fmt.Errorf("core HTTP %s",r.Status)};t:=corePath+".tmp";f,e:=os.OpenFile(t,os.O_CREATE|os.O_WRONLY|os.O_TRUNC,0700);if e!=nil{return e};_,e=io.Copy(f,r.Body);_=f.Close();if e!=nil{return e};return os.Rename(t,corePath)}
func(g *Gateway)connect()error{g.mu.Lock();if g.cmd!=nil{g.mu.Unlock();return nil};c:=g.cfg;g.mu.Unlock();if c.Peer==""||c.Password==""||c.Hashes==""{return fmt.Errorf("peer/password/hashes required")};if e:=g.setupWG();e!=nil{return e};if e:=g.setupTun();e!=nil{return e};if e:=g.setupPolicy();e!=nil{return e};a:=[]string{"--peer",c.Peer,"--password",c.Password,"--vk",c.Hashes,"--vk-hash-mode","manual","--vk-auth-mode",c.VKAuthMode,"--listen","127.0.0.1:0","-n",strconv.Itoa(c.Workers),"--obfs",c.Obfs,"--fingerprint",c.Fingerprint,"--client-ids",c.ClientIDs,"--captcha-mode",c.CaptchaMode,"--turn-transport",c.TurnTransport,"--device-id",c.DeviceID,"--tun-uds",uds};if c.TurnHost!=""{a=append(a,"--turn",c.TurnHost)};if c.TurnPort!=""{a=append(a,"--port",c.TurnPort)};cmd:=exec.Command(corePath,a...);out,e:=cmd.StdoutPipe();if e!=nil{return e};cmd.Stderr=cmd.Stdout;if e=cmd.Start();e!=nil{return e};if e=g.sendFD();e!=nil{_=cmd.Process.Kill();return fmt.Errorf("send TUN FD: %w",e)};g.mu.Lock();g.cmd=cmd;g.connected=true;g.started=time.Now();g.mu.Unlock();g.log("[CORE] started pid=%d",cmd.Process.Pid);go g.readCore(out);go func(){e:=cmd.Wait();g.mu.Lock();g.cmd=nil;g.connected=false;g.mu.Unlock();g.log("[CORE] stopped: %v",e);_=g.cleanupPolicy();_=g.cleanupTun()}();return nil}
func(g *Gateway)readCore(r io.Reader){s:=bufio.NewScanner(r);for s.Scan(){x:=s.Text();g.log("[CORE] %s",x);if i:=strings.Index(x,"TUNCONF:");i>=0{p:=strings.SplitN(strings.TrimPrefix(strings.TrimSpace(x[i:]),"TUNCONF:"),":",3);if len(p)>0{_=g.setTunIP(p[0])}}}}
func(g *Gateway)disconnect()error{g.mu.Lock();c:=g.cmd;g.mu.Unlock();if c!=nil&&c.Process!=nil{_=c.Process.Signal(syscall.SIGTERM);time.Sleep(1500*time.Millisecond);if c.ProcessState==nil||!c.ProcessState.Exited(){_=c.Process.Kill()}};_=g.cleanupPolicy();return g.cleanupTun()}
func(g *Gateway)setupWG()error{if _,e:=exec.Command("ip","link","show",wgName).CombinedOutput();e!=nil{if o,x:=exec.Command("ip","link","add","dev",wgName,"type","wireguard").CombinedOutput();x!=nil{return fmt.Errorf("WG: %s",strings.TrimSpace(string(o)))}};if e:=exec.Command("ip","addr","replace",wgServer,"dev",wgName).Run();e!=nil{return e};if e:=exec.Command("ip","link","set",wgName,"up").Run();e!=nil{return e};if e:=exec.Command("wg","set",wgName,"private-key","/etc/lalune/wg-private.key","listen-port",wgPort).Run();e!=nil{return e};g.mu.Lock();p:=strings.TrimSpace(g.cfg.WGPeerPublicKey);g.mu.Unlock();if p!=""{if e:=exec.Command("wg","set",wgName,"peer",p,"allowed-ips",wgPeer,"persistent-keepalive","25").Run();e!=nil{return e}};return nil}
func(g *Gateway)setupTun()error{_=exec.Command("ip","tuntap","del","dev",tunName,"mode","tun").Run();if e:=exec.Command("ip","tuntap","add","dev",tunName,"mode","tun").Run();e!=nil{return e};if e:=exec.Command("ip","addr","replace",tunIP+"/32","dev",tunName).Run();e!=nil{return e};if e:=exec.Command("ip","link","set",tunName,"up","mtu","1300").Run();e!=nil{return e};f,e:=os.OpenFile("/dev/net/tun",os.O_RDWR,0);if e!=nil{return e};if e=tunSetIFF(int(f.Fd()),tunName);e!=nil{_=f.Close();return e};g.tun=f;return nil}
func tunSetIFF(fd int,n string)error{const TUNSETIFF=0x400454CA;const IFF_TUN=1;const IFF_NO_PI=0x1000;var x [40]byte;copy(x[:16],n);*(*uint16)(unsafe.Pointer(&x[16]))=IFF_TUN|IFF_NO_PI;_,_,e:=syscall.Syscall(syscall.SYS_IOCTL,uintptr(fd),TUNSETIFF,uintptr(unsafe.Pointer(&x[0])));if e!=0{return e};return nil}
func(g *Gateway)sendFD()error{c,e:=net.DialUnix("unix",nil,&net.UnixAddr{Name:"\x00lalune-csqtt-tun",Net:"unix"});if e!=nil{return e};defer c.Close();if _,_,e=c.WriteMsgUnix([]byte{1},syscall.UnixRights(int(g.tun.Fd())),nil);e!=nil{return e};_=c.SetReadDeadline(time.Now().Add(5*time.Second));b:=make([]byte,1);_,e=c.Read(b);return e}
func(g *Gateway)setTunIP(ip string)error{if net.ParseIP(ip)==nil{return nil};if e:=exec.Command("ip","addr","replace",ip+"/32","dev",tunName).Run();e!=nil{return e};_=exec.Command("iptables","-t","nat","-F","LALUNE_POST").Run();_=exec.Command("iptables","-t","nat","-A","LALUNE_POST","-s",wgPeer,"-o",tunName,"-j","SNAT","--to-source",ip).Run();return nil}
func(g *Gateway)setupPolicy()error{cs:=[][]string{{"ip","route","replace",wgSubnet,"dev",wgName,"table",table},{"ip","route","replace","default","dev",tunName,"table",table},{"ip","rule","add","pref","22000","from",wgPeer,"lookup",table}};for _,c:=range cs{if o,e:=exec.Command(c[0],c[1:]...).CombinedOutput();e!=nil{return fmt.Errorf("%v: %s: %w",c,strings.TrimSpace(string(o)),e)}};_=exec.Command("iptables","-t","nat","-N","LALUNE_POST").Run();_=exec.Command("iptables","-t","nat","-F","LALUNE_POST").Run();_=exec.Command("iptables","-t","nat","-A","LALUNE_POST","-s",wgPeer,"-o",tunName,"-j","SNAT","--to-source",tunIP).Run();if e:=exec.Command("iptables","-t","nat","-C","POSTROUTING","-j","LALUNE_POST").Run();e!=nil{_=exec.Command("iptables","-t","nat","-A","POSTROUTING","-j","LALUNE_POST").Run()};return nil}
func(g *Gateway)cleanupPolicy()error{_=exec.Command("ip","rule","del","pref","22000","from",wgPeer,"lookup",table).Run();_=exec.Command("ip","route","flush","table",table).Run();_=exec.Command("iptables","-t","nat","-D","POSTROUTING","-j","LALUNE_POST").Run();_=exec.Command("iptables","-t","nat","-F","LALUNE_POST").Run();_=exec.Command("iptables","-t","nat","-X","LALUNE_POST").Run();return nil}
func(g *Gateway)cleanupTun()error{if g.tun!=nil{_=g.tun.Close();g.tun=nil};_=exec.Command("ip","tuntap","del","dev",tunName,"mode","tun").Run();return nil}
func(g *Gateway)status(w http.ResponseWriter,_ *http.Request){g.mu.Lock();defer g.mu.Unlock();_=json.NewEncoder(w).Encode(map[string]any{"connected":g.connected,"started":g.started,"tun":tunName,"table":table,"wg":wgName,"wgEndpoint":"192.168.4.26:"+wgPort,"wgPublicKey":readTrim("/etc/lalune/wg-public.key"),"config":g.cfg})}
func(g *Gateway)configAPI(w http.ResponseWriter,r *http.Request){if r.Method=="GET"{g.mu.Lock();defer g.mu.Unlock();_=json.NewEncoder(w).Encode(g.cfg);return};var c Config;if e:=json.NewDecoder(r.Body).Decode(&c);e!=nil{http.Error(w,"bad json",400);return};if e:=saveConfig(c);e!=nil{http.Error(w,e.Error(),500);return};g.mu.Lock();g.cfg=c;g.mu.Unlock();_=json.NewEncoder(w).Encode(map[string]bool{"ok":true})}
func(g *Gateway)connectAPI(w http.ResponseWriter,_ *http.Request){if e:=g.connect();e!=nil{http.Error(w,e.Error(),500);return};_=json.NewEncoder(w).Encode(map[string]bool{"ok":true})}
func(g *Gateway)disconnectAPI(w http.ResponseWriter,_ *http.Request){if e:=g.disconnect();e!=nil{http.Error(w,e.Error(),500);return};_=json.NewEncoder(w).Encode(map[string]bool{"ok":true})}
func(g *Gateway)logsAPI(w http.ResponseWriter,_ *http.Request){g.mu.Lock();defer g.mu.Unlock();_=json.NewEncoder(w).Encode(g.logs)}
func(g *Gateway)auth(next http.HandlerFunc)http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){t:=readTrim(tokenPath);if r.URL.Query().Get("token")!=t&&strings.TrimPrefix(r.Header.Get("Authorization"),"Bearer ")!=t{http.Error(w,"unauthorized",401);return};next(w,r)}}
func(g *Gateway)page(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");io.WriteString(w,"<!doctype html><html lang='ru'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>LaLune Gateway</title><style>body{font-family:system-ui;background:#0b1020;color:#eee;max-width:900px;margin:30px auto;padding:0 16px}textarea{width:100%;box-sizing:border-box;background:#11182b;color:#eee;border:1px solid #334}button{font:inherit;padding:8px;margin:4px;cursor:pointer}pre{background:#080c16;padding:12px;overflow:auto}</style><h1>LaLune Gateway</h1><div id='s'></div><h2>CSQTT</h2><textarea id='cfg' rows='16'></textarea><br><button onclick='save()'>Сохранить</button><button onclick='connect()'>Подключить</button><button onclick='disconnect()'>Отключить</button><h2>Лог</h2><pre id='l'></pre><script>async function j(u,o){return fetch(u,o).then(r=>r.json())};async function refresh(){let s=await j('/api/status');document.getElementById('s').textContent=(s.connected?'CONNECTED':'STOPPED')+' | TUN '+s.tun+' | table '+s.table+' | WG '+s.wgEndpoint+' | '+s.wgPublicKey;document.getElementById('cfg').value=JSON.stringify(s.config,null,2);document.getElementById('l').textContent=(await j('/api/logs')).join('\\n')}async function save(){await j('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:document.getElementById('cfg').value});refresh()}async function connect(){await j('/api/connect',{method:'POST'});refresh()}async function disconnect(){await j('/api/disconnect',{method:'POST'});refresh()}refresh();setInterval(refresh,2000)</script></html>")}
func readTrim(p string)string{b,_:=os.ReadFile(p);return strings.TrimSpace(string(b))}
